### ISSUE TITLE
Play sound on timer independently from OS notifications

### ISSUE THREAD

**Issue by dpolivaev** [mrozbarry/mobtime#102] opened 2020-07-31 15:03 UTC
Currently, there is only one way to be notified when the timer is up namely using showing OS notification. This approach has different disadvantages which I am going to describe here later. Therefore it would be nice if mobtime could play its own sound when the time is up. Ideally the user should be able to configure which kind of notification they prefer.

Relying on the system notifications has following disadvantages:
1. On Windows the played sound is not specific to the app and notification.
2. On Windows if notification sounds are disabled no sound is played when the time is up.
3. On Ubuntu I was not even able to activate any sounds on notifications, so no sound is played generally
4. On Ubuntu the notification text is broken as it displays a link to the originating website as  HTML code (see attached screen shot). It is not a mobtime specific problem. 
![notification-ubuntu-chrome](https://user-images.githubusercontent.com/1558052/89047982-76f70a00-d34f-11ea-9204-d01c4139b0d6.png)

So it would be nice to be able to use mobtime and have audio notification when the time is up without using the OS specific notifications

**Comment by dpolivaev** [comment] 2020-07-31 15:07
Solving this issue would probably also resolve https://github.com/mrozbarry/mobtime/issues/90

**Comment by dpolivaev** [comment] 2020-07-31 16:58
Could you give me some feedback on this issue?

**Comment by mrozbarry** [comment] 2020-07-31 17:42
What sort of feedback do you need?

**Comment by dpolivaev** [comment] 2020-07-31 17:45
Whether you agree with the suggestion or have any remarks

**Comment by mrozbarry** [comment] 2020-07-31 17:46
I think I'll consider this a duplicate of #90, which is on the roadmap, so I think it's valid.

**Comment by dpolivaev** [comment] 2020-07-31 18:39
Thanks for the update

**Closed** 2020-08-13 14:40 UTC
Labels: duplicate
